module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "hotfix",
        "refactor",
        "perf",
        "test",
        "docs",
        "chore",
        "build",
        "ci",
        "security",
        "revert",
      ],
    ],
    "scope-enum": [
      2,
      "always",
      [
        "repo",
        "core",
        "domain",
        "ports",
        "rag",
        "router",
        "guardrails",
        "auth",
        "tenant",
        "chunking",
        "embedding",
        "vectorstore",
        "cache",
        "eventbus",
        "persistence",
        "api",
        "admin",
        "workers",
        "frontend",
        "chat",
        "eval",
        "docker",
        "ci",
        "deps",
      ],
    ],
    "subject-case": [2, "never", ["start-case", "pascal-case", "upper-case"]],
    "header-max-length": [2, "always", 72],
  },
};
