"""add policy_type to flagged_responses

Revision ID: 59b154e773c6
Revises: d7ad8824e70e
Create Date: 2026-08-25 20:37:03.400075

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "59b154e773c6"
down_revision: str | None = "d7ad8824e70e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flagged_responses",
        sa.Column(
            "policy_type",
            sa.Enum("HEALTH", "DENTAL", "VISION", "LIFE", "DISABILITY", name="policy_type"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flagged_responses", "policy_type")
    # ### end Alembic commands ###
