"""initial schema

Revision ID: c66afd6b3aeb
Revises:
Create Date: 2026-08-23 19:25:28.637295

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c66afd6b3aeb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Postgres ENUM types used by columns below. Alembic's autogenerated
# create_table auto-creates a named enum type on first use, but op.drop_table
# does NOT auto-drop the type afterward (unlike a full SQLAlchemy
# Table.drop()) — so every one of these must be created/dropped explicitly
# here, once each, with create_type=False on the columns that use them,
# rather than relying on implicit per-column create/drop. Without this,
# downgrade-then-upgrade fails with "type ... already exists".
policy_type_enum = postgresql.ENUM(
    "HEALTH", "DENTAL", "VISION", "LIFE", "DISABILITY", name="policy_type", create_type=False
)
user_role_enum = postgresql.ENUM(
    "ADMIN", "EMPLOYER", "EMPLOYEE", name="user_role", create_type=False
)
document_status_enum = postgresql.ENUM(
    "PROCESSING", "READY", "FAILED", name="document_status", create_type=False
)
message_role_enum = postgresql.ENUM("USER", "ASSISTANT", name="message_role", create_type=False)
feedback_rating_enum = postgresql.ENUM(
    "THUMBS_UP", "THUMBS_DOWN", name="feedback_rating", create_type=False
)
flagged_response_status_enum = postgresql.ENUM(
    "PENDING_REVIEW",
    "REVIEWED",
    "DISMISSED",
    name="flagged_response_status",
    create_type=False,
)

ALL_ENUMS = (
    policy_type_enum,
    user_role_enum,
    document_status_enum,
    message_role_enum,
    feedback_rating_enum,
    flagged_response_status_enum,
)


def upgrade() -> None:
    bind = op.get_bind()
    for enum_type in ALL_ENUMS:
        enum_type.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("employer_id", sa.Uuid(), nullable=False),
        sa.Column("policy_type", policy_type_enum, nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("source_path", sa.String(length=1024), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", document_status_enum, nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["employer_id"],
            ["employers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_employer_id"), "documents", ["employer_id"], unique=False)
    op.create_table(
        "employees",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("employer_id", sa.Uuid(), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("role", user_role_enum, nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["employer_id"],
            ["employers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_employees_email"),
    )
    op.create_index(op.f("ix_employees_employer_id"), "employees", ["employer_id"], unique=False)
    op.create_table(
        "guardrail_rejections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("employer_id", sa.Uuid(), nullable=False),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("rejection_reason", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["employer_id"],
            ["employers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_guardrail_rejections_employer_id"),
        "guardrail_rejections",
        ["employer_id"],
        unique=False,
    )
    op.create_table(
        "llm_cost_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("employer_id", sa.Uuid(), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("model_tier", sa.String(length=16), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Float(), nullable=False),
        sa.Column("query_complexity_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["employer_id"],
            ["employers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_llm_cost_logs_employer_id"), "llm_cost_logs", ["employer_id"], unique=False
    )
    op.create_table(
        "policies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("employer_id", sa.Uuid(), nullable=False),
        sa.Column("policy_type", policy_type_enum, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["employer_id"],
            ["employers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_policies_employer_id"), "policies", ["employer_id"], unique=False)
    op.create_table(
        "request_latency_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("employer_id", sa.Uuid(), nullable=False),
        sa.Column("total_ms", sa.Integer(), nullable=False),
        sa.Column("retrieval_ms", sa.Integer(), nullable=True),
        sa.Column("llm_ms", sa.Integer(), nullable=True),
        sa.Column("overhead_ms", sa.Integer(), nullable=True),
        sa.Column("model_tier", sa.String(length=16), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["employer_id"],
            ["employers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_request_latency_logs_employer_id"),
        "request_latency_logs",
        ["employer_id"],
        unique=False,
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("employer_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employer_id"],
            ["employers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversations_employee_id"), "conversations", ["employee_id"], unique=False
    )
    op.create_index(
        op.f("ix_conversations_employer_id"), "conversations", ["employer_id"], unique=False
    )
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("employer_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("section_title", sa.String(length=512), nullable=True),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employer_id"],
            ["employers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_chunks_document_id"), "document_chunks", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_chunks_employer_id"), "document_chunks", ["employer_id"], unique=False
    )
    op.create_table(
        "employee_policies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("enrolled_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_id", "policy_id", name="uq_employee_policy"),
    )
    op.create_index(
        op.f("ix_employee_policies_employee_id"), "employee_policies", ["employee_id"], unique=False
    )
    op.create_index(
        op.f("ix_employee_policies_policy_id"), "employee_policies", ["policy_id"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("employer_id", sa.Uuid(), nullable=False),
        sa.Column("role", message_role_enum, nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("model_used", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employer_id"],
            ["employers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_messages_employer_id"), "messages", ["employer_id"], unique=False)
    op.create_table(
        "feedback",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("employer_id", sa.Uuid(), nullable=False),
        sa.Column("rating", feedback_rating_enum, nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employer_id"],
            ["employers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_feedback_conversation_id"), "feedback", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_feedback_employer_id"), "feedback", ["employer_id"], unique=False)
    op.create_index(op.f("ix_feedback_message_id"), "feedback", ["message_id"], unique=False)
    op.create_table(
        "flagged_responses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("employer_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("top_similarity_score", sa.Float(), nullable=True),
        sa.Column("flag_reason", sa.String(length=128), nullable=False),
        sa.Column("status", flagged_response_status_enum, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employer_id"],
            ["employers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_flagged_responses_conversation_id"),
        "flagged_responses",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flagged_responses_employer_id"), "flagged_responses", ["employer_id"], unique=False
    )
    op.create_index(
        op.f("ix_flagged_responses_message_id"), "flagged_responses", ["message_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_flagged_responses_message_id"), table_name="flagged_responses")
    op.drop_index(op.f("ix_flagged_responses_employer_id"), table_name="flagged_responses")
    op.drop_index(op.f("ix_flagged_responses_conversation_id"), table_name="flagged_responses")
    op.drop_table("flagged_responses")
    op.drop_index(op.f("ix_feedback_message_id"), table_name="feedback")
    op.drop_index(op.f("ix_feedback_employer_id"), table_name="feedback")
    op.drop_index(op.f("ix_feedback_conversation_id"), table_name="feedback")
    op.drop_table("feedback")
    op.drop_index(op.f("ix_messages_employer_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_employee_policies_policy_id"), table_name="employee_policies")
    op.drop_index(op.f("ix_employee_policies_employee_id"), table_name="employee_policies")
    op.drop_table("employee_policies")
    op.drop_index(op.f("ix_document_chunks_employer_id"), table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_document_id"), table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index(op.f("ix_conversations_employer_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_employee_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_request_latency_logs_employer_id"), table_name="request_latency_logs")
    op.drop_table("request_latency_logs")
    op.drop_index(op.f("ix_policies_employer_id"), table_name="policies")
    op.drop_table("policies")
    op.drop_index(op.f("ix_llm_cost_logs_employer_id"), table_name="llm_cost_logs")
    op.drop_table("llm_cost_logs")
    op.drop_index(op.f("ix_guardrail_rejections_employer_id"), table_name="guardrail_rejections")
    op.drop_table("guardrail_rejections")
    op.drop_index(op.f("ix_employees_employer_id"), table_name="employees")
    op.drop_table("employees")
    op.drop_index(op.f("ix_documents_employer_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_table("employers")
    # ### end Alembic commands ###

    bind = op.get_bind()
    for enum_type in ALL_ENUMS:
        enum_type.drop(bind, checkfirst=True)
